---
dist: trusty
sudo: required
services:
  - docker
env:
  matrix:
    - FILEXT=ttl
    - FILEXT=jsonld
install:
  - docker build -t linnae/sfb-annotator:local .
  - docker run --name sea -d -p 8080:8080 linnae/sfb-annotator:local
  - sleep 10
  - docker exec sea ./init.sh
script:
  - |
    for json in $(ls data/json/*.json|sort); do
      prefix="$(basename "$json" .json)"
      rdf="$prefix.$FILEXT"
      ./run.sh "$json" "$rdf"
    done
