---
dist: trusty
sudo: required
services:
  - docker
env:
  global:
    - PORT=8080
    - BASE_URL=http://localhost:${PORT}
install:
  - docker-compose up -d
  - sleep 10
  - docker-compose exec sea ./init.sh
script:
  - |
    PATHS=(semanticAnnotator/files/MMNAT01_AF_NNM001000283.jpg rdf4j-workbench/repositories/mem-rdf/summary)
    for p in ${PATHS[@]}; do
      [[ $(curl -u tomcat:tomcat -o -I -w "%{http_code}" "$BASE_URL/$p") -eq 200 ]]
    done
