---
dist: trusty
sudo: required
services:
  - docker
env:
  global:
    - IMG_NAME=sea
    - PORT=8080
    - URL=http://localhost:${PORT}/semanticAnnotator/files/MMNAT01_AF_NNM001000283.jpg
install:
  - docker build -t $IMG_NAME .
  - docker run -d -p $PORT:$PORT $IMG_NAME
  - sleep 10
script:
  - |
    [[ $(curl -u tomcat:tomcat -o -I -w "%{http_code}" $URL) -eq 200 ]]
