---
dist: bioinic
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - CRE=tomcat:tomcat
    - BASE=/usr/local/tomcat/webapps/semanticAnnotator/data/
  matrix:
    - IMG_SRC=local
    - IMG_SRC=remote
install:
  - pip install -q jq tripoli
  - docker-compose up -d
  - docker exec sea ./init.sh
  - docker exec sea bash -c "cp $BASE/data-$IMG_SRC.json $BASE/data.json && cat \$_"
script:
  - |
    echo "Check the accessibility of image files..."
    for url in $(jq -r ".items|.[].item[]" < ./src/main/webapp/data/data-$IMG_SRC.json); do
      echo -ne "$url\t ..."
      [[ $(curl -s -u "$CRE" -w "%{http_code}" "$url" -o /dev/null) -eq 200 ]] \
        && echo "OK" || (echo "FAILED" && exit 1)
    done
  - |
    for json in $(ls data/json/*.json | sort); do
      prefix="$(basename "$json" .json)"
      rdf="$prefix.ttl"
      ./run.sh "$json" "$rdf"
    done
  - ./validate.py data/manifest.json
