---
dist: trusty
sudo: required
services:
  - docker
env:
  global:
    - RDF_SUFFIX=ttl
    - BASE=/usr/local/tomcat/webapps/semanticAnnotator/data/
  matrix:
    - JSON=data-local.json
    - JSON=data-sdr.json
install:
  - docker-compose up -d
  - docker exec -t sea ./init.sh
  - docker exec -t sea bash -c "cp -f $BASE/$JSON $BASE/data.json"
script:
  -
    for json in $(ls data/json/*.json|sort); do
      prefix="$(basename "$json" .json)"
      rdf="$prefix.$RDF_SUFFIX"
      ./run.sh "$json" "$rdf"
    done
