---
dist: trusty
sudo: required
services:
  - docker
env:
  global:
    - BASE=/usr/local/tomcat/webapps/semanticAnnotator/data/
  matrix:
    - IMG=local
    - IMG=remote
install:
  - docker-compose up -d
  - sleep 10
  - docker exec sea ./init.sh
  - docker exec sea bash -c "cp $BASE/data-$IMG.json $BASE/data.json && cat \$_"
script:
  - |
    for json in $(ls data/json/*.json | sort); do
      prefix="$(basename "$json" .json)"
      rdf="$prefix.ttl"
      ./run.sh "$json" "$rdf"
    done
