---
dist: trusty
sudo: required
services:
  - docker
env:
  global:
    - IMG=sea
    - PORT=8080
    - URL=http://localhost:${PORT}/semanticAnnotator/
install:
  - docker build -t $IMG .
  - docker run -d -p $PORT:$PORT $IMG
  - sleep 10
script:
  - |
    [[ $(curl -u tomcat:tomcat -o -I -w "%{http_code}" $URL) -eq 200 ]]
