name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Echo variables
        run: echo $CRE $BASE $PREFIX $IMG_SRC
        env:
          CRE: tomcat:tomcat
          BASE: /usr/local/tomcat/webapps/semanticAnnotator/data/
          PREFIX: ./src/main/webapp/data/data
          IMG_SRC: local
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q jq tripoli
      - name: Show pip list
        run: pip list
      - name: Start services
        run: docker-compose up -d
      - name: Configure services
        run: |
          docker exec sea ./init.sh
          docker exec sea bash -c \
            "cp $BASE/data-$IMG_SRC.json $BASE/data.json && cat \$_"
